### ISSUE TITLE
docker.lua prevents the use of the `--name` flag

### ISSUE THREAD

**Issue by Riduidel** [sebthom/more-clink-completions#2]
I want to try to run the following docker command

```
docker run -d --name kroki --restart unless-stopped -p29000:8000 yuzutech/kroki
```

But I can't run the command because i'm interrupted by the error message

```
unknown flag: --name
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers
```

As soon as I enter the `--name` flag

**Comment by sebthom** [comment]
First I cannot reproduce this on my system and I don't think this issue is caused by the completions provided in this repo. Maybe a bug in clink itself.

Anyways, I refactored all completions. Please give the new version a try and see if your issue persists.

The installation steps have changed please check https://github.com/sebthom/more-clink-completions#installation
